### ISSUE TITLE
Point users to up-to-date documentation

### ISSUE THREAD

**Issue by codecat** [The-Firexx/trackmania2020apidocumentation#15]
We are maintaining an up-to-date documentation here: https://webservices.openplanet.dev/

It would be nice if this repository links there, preferably at the very top of the Readme file, so people don't get confused with outdated and incorrect information here.

**Comment by The-Firexx** [comment]
Hello
Sorry if 4 months have pass before I see this.
You are right, I will update this repository to redirect visitors to that website.
Thank you for your efforts!
